//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.LocalDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones_DiasPendientes
    {
        public int Id { get; set; }
        public string NombreCiaContab { get; set; }
        public string NombreDepartamento { get; set; }
        public int Empleado { get; set; }
        public string NombreEmpleado { get; set; }
        public string AliasEmpleado { get; set; }
        public int NumeroVacacion { get; set; }
        public System.DateTime AnoVacacionDesde { get; set; }
        public System.DateTime AnoVacacionHasta { get; set; }
        public int CantidadDiasVacacionesSegunTabla { get; set; }
        public int CantidadDiasAnoParaCalculoProrrata { get; set; }
        public decimal FactorProrrata { get; set; }
        public int CantidadDiasVacacionesSegunTablaProrrata { get; set; }
        public int VacacionesDisfrutadas_Cantidad { get; set; }
        public Nullable<System.DateTime> VacacionesDisfrutadas_Desde1raVacacion { get; set; }
        public Nullable<System.DateTime> VacacionesDisfrutadas_HastaUltimaVacacion { get; set; }
        public int VacacionesDisfrutadas_TotalDias { get; set; }
        public int VacacionesDisfrutadas_TotalDiasFeriados { get; set; }
        public int VacacionesDisfrutadas_TotalDiasDisfrutados { get; set; }
        public int DiasPendientes_AnosAnteriores { get; set; }
        public int DiasPendientes_EsteAno { get; set; }
        public int DiasPendientes_Total { get; set; }
        public System.DateTime FRegistro { get; set; }
        public string Usuario { get; set; }
    }
}
