//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompaniasYUsuario
    {
        public int PK { get; set; }
        public int Compania { get; set; }
        public System.Guid Usuario { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Compania Compania1 { get; set; }
    }
}
