//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania
    {
        public Compania()
        {
            this.CompaniasYUsuarios = new HashSet<CompaniasYUsuario>();
            this.tCiaSeleccionadas = new HashSet<tCiaSeleccionada2>();
        }
    
        public int Numero { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public string Abreviatura { get; set; }
        public string Rif { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string EntidadFederal { get; set; }
        public string ZonaPostal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string EmailServerName { get; set; }
        public Nullable<int> EmailServerPort { get; set; }
        public Nullable<bool> EmailServerSSLFlag { get; set; }
        public string EmailServerCredentialsUserName { get; set; }
        public string EmailServerCredentialsPassword { get; set; }
        public Nullable<int> MonedaDefecto { get; set; }
        public Nullable<bool> SuspendidoFlag { get; set; }
    
        public virtual ICollection<CompaniasYUsuario> CompaniasYUsuarios { get; set; }
        public virtual ICollection<tCiaSeleccionada2> tCiaSeleccionadas { get; set; }
    }
}
