//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCiaSeleccionada2
    {
        public int ID { get; set; }
        public int CiaSeleccionada { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public int Usuario { get; set; }
        public string UsuarioLS { get; set; }
    
        public virtual Compania Compania { get; set; }
    }
}
