//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banco()
        {
            this.tEmpleados = new HashSet<tEmpleado>();
            this.tEmpleados1 = new HashSet<tEmpleado>();
        }
    
        public int Banco1 { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public string Abreviatura { get; set; }
        public Nullable<int> DefinicionParaElArchivo { get; set; }
        public string NombreArchivoDeTexto { get; set; }
        public string Codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEmpleado> tEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEmpleado> tEmpleados1 { get; set; }
    }
}
