//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compania()
        {
            this.tGruposEmpleados = new HashSet<tGruposEmpleado>();
            this.tCiaSeleccionadas = new HashSet<tCiaSeleccionada>();
            this.CuentasContables = new HashSet<CuentasContable>();
            this.tCuentasContablesPorEmpleadoYRubroes = new HashSet<tCuentasContablesPorEmpleadoYRubro>();
            this.DeduccionesNominas = new HashSet<DeduccionesNomina>();
            this.PrestacionesSocialesHeaders = new HashSet<PrestacionesSocialesHeader>();
            this.tEmpleados = new HashSet<tEmpleado>();
            this.Asientos = new HashSet<Asiento>();
        }
    
        public int Numero { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public string Abreviatura { get; set; }
        public string Rif { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string EntidadFederal { get; set; }
        public string ZonaPostal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string EmailServerName { get; set; }
        public Nullable<int> EmailServerPort { get; set; }
        public Nullable<bool> EmailServerSSLFlag { get; set; }
        public string EmailServerCredentialsUserName { get; set; }
        public string EmailServerCredentialsPassword { get; set; }
        public Nullable<int> MonedaDefecto { get; set; }
        public Nullable<bool> SuspendidoFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGruposEmpleado> tGruposEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCiaSeleccionada> tCiaSeleccionadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasContable> CuentasContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCuentasContablesPorEmpleadoYRubro> tCuentasContablesPorEmpleadoYRubroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeduccionesNomina> DeduccionesNominas { get; set; }
        public virtual ParametrosNomina ParametrosNomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestacionesSocialesHeader> PrestacionesSocialesHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEmpleado> tEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asientos { get; set; }
    }
}
