//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasContable()
        {
            this.tCuentasContablesPorEmpleadoYRubroes = new HashSet<tCuentasContablesPorEmpleadoYRubro>();
            this.ParametrosNominas = new HashSet<ParametrosNomina>();
        }
    
        public int ID { get; set; }
        public string Cuenta { get; set; }
        public string Descripcion { get; set; }
        public string Nivel1 { get; set; }
        public string Nivel2 { get; set; }
        public string Nivel3 { get; set; }
        public string Nivel4 { get; set; }
        public string Nivel5 { get; set; }
        public string Nivel6 { get; set; }
        public string Nivel7 { get; set; }
        public byte NumNiveles { get; set; }
        public string TotDet { get; set; }
        public string ActSusp { get; set; }
        public Nullable<int> Estructura { get; set; }
        public string CuentaEditada { get; set; }
        public string Modelo { get; set; }
        public int Grupo { get; set; }
        public string NivelAgrupacion { get; set; }
        public Nullable<int> GrupoNivelAgrupacion { get; set; }
        public Nullable<bool> PresupuestarFlag { get; set; }
        public int Cia { get; set; }
    
        public virtual Compania Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCuentasContablesPorEmpleadoYRubro> tCuentasContablesPorEmpleadoYRubroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametrosNomina> ParametrosNominas { get; set; }
    }
}
