//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeduccionesISLR
    {
        public int ID { get; set; }
        public Nullable<int> GrupoNomina { get; set; }
        public Nullable<int> Empleado { get; set; }
        public System.DateTime Desde { get; set; }
        public string TipoNomina { get; set; }
        public string Periodicidad { get; set; }
        public decimal Porcentaje { get; set; }
        public string Base { get; set; }
        public bool SuspendidoFlag { get; set; }
    
        public virtual tGruposEmpleado tGruposEmpleado { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
