//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeduccionesNomina
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Desde { get; set; }
        public Nullable<int> Cia { get; set; }
        public Nullable<int> GrupoNomina { get; set; }
        public Nullable<int> GrupoEmpleados { get; set; }
        public Nullable<int> Empleado { get; set; }
        public decimal AporteEmpleado { get; set; }
        public decimal AporteEmpresa { get; set; }
        public string Base { get; set; }
        public Nullable<decimal> Tope { get; set; }
        public string TopeBase { get; set; }
        public bool SuspendidoFlag { get; set; }
    
        public virtual Compania Compania { get; set; }
        public virtual tGruposEmpleado tGruposEmpleado { get; set; }
        public virtual tGruposEmpleado tGruposEmpleado1 { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
