//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados_Faltas
    {
        public int ID { get; set; }
        public int Empleado { get; set; }
        public System.DateTime Desde { get; set; }
        public System.DateTime Hasta { get; set; }
        public short CantDias { get; set; }
        public short CantDiasSabDom { get; set; }
        public short CantDiasFeriados { get; set; }
        public short CantDiasHabiles { get; set; }
        public Nullable<short> CantHoras { get; set; }
        public bool Descontar { get; set; }
        public Nullable<System.DateTime> Descontar_FechaNomina { get; set; }
        public Nullable<int> Descontar_GrupoNomina { get; set; }
        public string Base { get; set; }
        public string Observaciones { get; set; }
        public string DescripcionRubroNomina { get; set; }
    
        public virtual tGruposEmpleado tGruposEmpleado { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
