//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina_DefinicionAnticipos_Empleados
    {
        public int ID { get; set; }
        public int DefinicionAnticiposID { get; set; }
        public int Empleado { get; set; }
        public bool Suspendido { get; set; }
        public Nullable<decimal> PrimQuincPorc { get; set; }
    
        public virtual Nomina_DefinicionAnticipos Nomina_DefinicionAnticipos { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
