//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbNominaEntities : DbContext
    {
        public dbNominaEntities()
            : base("name=dbNominaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compania> Companias { get; set; }
        public virtual DbSet<tGruposEmpleado> tGruposEmpleados { get; set; }
        public virtual DbSet<tCiaSeleccionada> tCiaSeleccionadas { get; set; }
        public virtual DbSet<Empleados_Sueldo> Empleados_Sueldo { get; set; }
        public virtual DbSet<tCargo> tCargos { get; set; }
        public virtual DbSet<tDepartamento> tDepartamentos { get; set; }
        public virtual DbSet<DiasFeriado> DiasFeriados { get; set; }
        public virtual DbSet<tCuotasPrestamo> tCuotasPrestamos { get; set; }
        public virtual DbSet<tPrestamo> tPrestamos { get; set; }
        public virtual DbSet<Parametros_Nomina_SalarioMinimo> Parametros_Nomina_SalarioMinimo { get; set; }
        public virtual DbSet<VacacPorAnoGenerica> VacacPorAnoGenericas { get; set; }
        public virtual DbSet<VacacPorAnoParticulare> VacacPorAnoParticulares { get; set; }
        public virtual DbSet<CambiosMoneda> CambiosMonedas { get; set; }
        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<CuentasContable> CuentasContables { get; set; }
        public virtual DbSet<tCuentasContablesPorEmpleadoYRubro> tCuentasContablesPorEmpleadoYRubroes { get; set; }
        public virtual DbSet<Nomina_DefinicionAnticipos> Nomina_DefinicionAnticipos { get; set; }
        public virtual DbSet<Nomina_DefinicionAnticipos_Empleados> Nomina_DefinicionAnticipos_Empleados { get; set; }
        public virtual DbSet<DeduccionesISLR> DeduccionesISLRs { get; set; }
        public virtual DbSet<DeduccionesNomina> DeduccionesNominas { get; set; }
        public virtual DbSet<ParametrosNomina> ParametrosNominas { get; set; }
        public virtual DbSet<tdGruposEmpleado> tdGruposEmpleados { get; set; }
        public virtual DbSet<Utilidade> Utilidades { get; set; }
        public virtual DbSet<Empleados_Faltas> Empleados_Faltas { get; set; }
        public virtual DbSet<tNomina_SalarioIntegral> tNomina_SalarioIntegral { get; set; }
        public virtual DbSet<tNomina> tNominas { get; set; }
        public virtual DbSet<Vacacione> Vacaciones { get; set; }
        public virtual DbSet<PrestacionesSocialesHeader> PrestacionesSocialesHeaders { get; set; }
        public virtual DbSet<PrestacionesSociale> PrestacionesSociales { get; set; }
        public virtual DbSet<tMaestraRubro> tMaestraRubros { get; set; }
        public virtual DbSet<tRubrosAsignado> tRubrosAsignados { get; set; }
        public virtual DbSet<tNominaHeader> tNominaHeaders { get; set; }
        public virtual DbSet<tEmpleado> tEmpleados { get; set; }
        public virtual DbSet<Asiento> Asientos { get; set; }
    }
}
