//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_Nomina_SalarioMinimo
    {
        public int ID { get; set; }
        public System.DateTime Desde { get; set; }
        public decimal Monto { get; set; }
    }
}
