//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosNomina
    {
        public Nullable<float> LimiteProrrateoVacaciones { get; set; }
        public Nullable<bool> AgregarAsientosContables { get; set; }
        public Nullable<bool> OrganizarPartidasDelAsiento { get; set; }
        public string TipoAsientoDefault { get; set; }
        public Nullable<int> CuentaContableNomina { get; set; }
        public Nullable<int> MonedaParaElAsiento { get; set; }
        public Nullable<short> SumarizarPartidaAsientoContable { get; set; }
        public string CodigoConceptoRetencionISLREmpleados { get; set; }
        public int Cia { get; set; }
    
        public virtual Compania Compania { get; set; }
        public virtual CuentasContable CuentasContable { get; set; }
    }
}
