//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestacionesSocialesHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrestacionesSocialesHeader()
        {
            this.PrestacionesSociales = new HashSet<PrestacionesSociale>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public short Mes { get; set; }
        public short Ano { get; set; }
        public short CantDiasUtilidades { get; set; }
        public bool AgregarMontoCestaTickets { get; set; }
        public int Cia { get; set; }
    
        public virtual Compania Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestacionesSociale> PrestacionesSociales { get; set; }
    }
}
