//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestacionesSociale
    {
        public int ID { get; set; }
        public int HeaderID { get; set; }
        public int Empleado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public short AnosServicio { get; set; }
        public short AnosServicioPrestaciones { get; set; }
        public bool PrimerMesPrestacionesFlag { get; set; }
        public Nullable<byte> CantidadDiasTrabajadosPrimerMes { get; set; }
        public decimal SueldoBasico { get; set; }
        public Nullable<decimal> MontoCestaTickets { get; set; }
        public Nullable<decimal> SueldoBasicoPrestaciones { get; set; }
        public decimal SueldoBasicoDiario { get; set; }
        public short DiasVacaciones { get; set; }
        public decimal BonoVacacional { get; set; }
        public decimal BonoVacacionalDiario { get; set; }
        public decimal Utilidades { get; set; }
        public decimal UtilidadesDiarias { get; set; }
        public decimal SueldoDiarioAumentado { get; set; }
        public short DiasPrestaciones { get; set; }
        public decimal MontoPrestaciones { get; set; }
        public bool AnoCumplidoFlag { get; set; }
        public Nullable<byte> CantidadDiasAdicionales { get; set; }
        public Nullable<decimal> MontoPrestacionesDiasAdicionales { get; set; }
    
        public virtual PrestacionesSocialesHeader PrestacionesSocialesHeader { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
