//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCuentasContablesPorEmpleadoYRubro
    {
        public int ClaveUnica { get; set; }
        public int Rubro { get; set; }
        public Nullable<int> Empleado { get; set; }
        public Nullable<int> Departamento { get; set; }
        public int CuentaContable { get; set; }
        public Nullable<short> SumarizarEnUnaPartidaFlag { get; set; }
        public int Cia { get; set; }
    
        public virtual Compania Compania { get; set; }
        public virtual CuentasContable CuentasContable { get; set; }
        public virtual tDepartamento tDepartamento { get; set; }
        public virtual tMaestraRubro tMaestraRubro { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
