//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCuotasPrestamo
    {
        public int ClavePrincipal { get; set; }
        public int Prestamo { get; set; }
        public System.DateTime FechaCuota { get; set; }
        public decimal Monto { get; set; }
        public Nullable<bool> Cancelada { get; set; }
        public Nullable<decimal> MontoIntereses { get; set; }
        public decimal TotalCuota { get; set; }
        public Nullable<bool> PagarPorNominaFlag { get; set; }
        public string TipoNomina { get; set; }
    
        public virtual tPrestamo tPrestamo { get; set; }
    }
}
