//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdGruposEmpleado
    {
        public int ClaveUnica { get; set; }
        public int Grupo { get; set; }
        public int Empleado { get; set; }
        public bool SuspendidoFlag { get; set; }
    
        public virtual tGruposEmpleado tGruposEmpleado { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
