//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEmpleado()
        {
            this.DeduccionesISLRs = new HashSet<DeduccionesISLR>();
            this.DeduccionesNominas = new HashSet<DeduccionesNomina>();
            this.Empleados_Faltas = new HashSet<Empleados_Faltas>();
            this.Empleados_Sueldo = new HashSet<Empleados_Sueldo>();
            this.Nomina_DefinicionAnticipos_Empleados = new HashSet<Nomina_DefinicionAnticipos_Empleados>();
            this.PrestacionesSociales = new HashSet<PrestacionesSociale>();
            this.tCuentasContablesPorEmpleadoYRubroes = new HashSet<tCuentasContablesPorEmpleadoYRubro>();
            this.tdGruposEmpleados = new HashSet<tdGruposEmpleado>();
            this.tNomina_SalarioIntegral = new HashSet<tNomina_SalarioIntegral>();
            this.tNominas = new HashSet<tNomina>();
            this.tPrestamos = new HashSet<tPrestamo>();
            this.tRubrosAsignados = new HashSet<tRubrosAsignado>();
            this.Vacaciones = new HashSet<Vacacione>();
            this.VacacPorAnoParticulares = new HashSet<VacacPorAnoParticulare>();
        }
    
        public int Empleado { get; set; }
        public string Cedula { get; set; }
        public string Alias { get; set; }
        public string Rif { get; set; }
        public short TipoNomina { get; set; }
        public Nullable<bool> EscribirArchivoXMLRetencionesISLR { get; set; }
        public string Status { get; set; }
        public string Nombre { get; set; }
        public string EdoCivil { get; set; }
        public string Sexo { get; set; }
        public string Nacionalidad { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string CiudadOrigen { get; set; }
        public string DireccionHabitacion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string email { get; set; }
        public string SituacionActual { get; set; }
        public int Departamento { get; set; }
        public int Cargo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public Nullable<int> BancoDepositosNomina { get; set; }
        public Nullable<int> TipoCuentaDepositosNomina { get; set; }
        public string CuentaBancariaDepositosNomina { get; set; }
        public Nullable<int> BancoCuentaPrestacionesSociales { get; set; }
        public string NumeroCuentaBancariaPrestacionesSociales { get; set; }
        public string Contacto1 { get; set; }
        public Nullable<int> Parentesco1 { get; set; }
        public string TelefonoCon1 { get; set; }
        public string Contacto2 { get; set; }
        public Nullable<int> Parentesco2 { get; set; }
        public string TelefonoCon2 { get; set; }
        public string Contacto3 { get; set; }
        public Nullable<int> Parentesco3 { get; set; }
        public string TelefonoCon3 { get; set; }
        public Nullable<short> EmpleadoObreroFlag { get; set; }
        public Nullable<decimal> MontoCestaTickets { get; set; }
        public Nullable<bool> BonoVacAgregarSueldoFlag { get; set; }
        public Nullable<bool> BonoVacAgregarMontoCestaTicketsFlag { get; set; }
        public Nullable<decimal> BonoVacacionalMontoAdicional { get; set; }
        public Nullable<bool> BonoVacAgregarMontoAdicionalFlag { get; set; }
        public Nullable<bool> PrestacionesAgregarMontoCestaTicketsFlag { get; set; }
        public int Cia { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Banco Banco1 { get; set; }
        public virtual Compania Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeduccionesISLR> DeduccionesISLRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeduccionesNomina> DeduccionesNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados_Faltas> Empleados_Faltas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados_Sueldo> Empleados_Sueldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina_DefinicionAnticipos_Empleados> Nomina_DefinicionAnticipos_Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestacionesSociale> PrestacionesSociales { get; set; }
        public virtual tCargo tCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCuentasContablesPorEmpleadoYRubro> tCuentasContablesPorEmpleadoYRubroes { get; set; }
        public virtual tDepartamento tDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tdGruposEmpleado> tdGruposEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNomina_SalarioIntegral> tNomina_SalarioIntegral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNomina> tNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPrestamo> tPrestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRubrosAsignado> tRubrosAsignados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacacione> Vacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacacPorAnoParticulare> VacacPorAnoParticulares { get; set; }
    }
}
