//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGruposEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGruposEmpleado()
        {
            this.Nomina_DefinicionAnticipos = new HashSet<Nomina_DefinicionAnticipos>();
            this.DeduccionesISLRs = new HashSet<DeduccionesISLR>();
            this.DeduccionesNominas = new HashSet<DeduccionesNomina>();
            this.DeduccionesNominas1 = new HashSet<DeduccionesNomina>();
            this.tdGruposEmpleados = new HashSet<tdGruposEmpleado>();
            this.Utilidades = new HashSet<Utilidade>();
            this.Empleados_Faltas = new HashSet<Empleados_Faltas>();
            this.Vacaciones = new HashSet<Vacacione>();
            this.tNominaHeaders = new HashSet<tNominaHeader>();
        }
    
        public int Grupo { get; set; }
        public string NombreGrupo { get; set; }
        public string Descripcion { get; set; }
        public bool GrupoNominaFlag { get; set; }
        public int Cia { get; set; }
    
        public virtual Compania Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina_DefinicionAnticipos> Nomina_DefinicionAnticipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeduccionesISLR> DeduccionesISLRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeduccionesNomina> DeduccionesNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeduccionesNomina> DeduccionesNominas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tdGruposEmpleado> tdGruposEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilidade> Utilidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados_Faltas> Empleados_Faltas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacacione> Vacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNominaHeader> tNominaHeaders { get; set; }
    }
}
