//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMaestraRubro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMaestraRubro()
        {
            this.tCuentasContablesPorEmpleadoYRubroes = new HashSet<tCuentasContablesPorEmpleadoYRubro>();
            this.tNominas = new HashSet<tNomina>();
            this.tRubrosAsignados = new HashSet<tRubrosAsignado>();
        }
    
        public int Rubro { get; set; }
        public string NombreCortoRubro { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> SueldoFlag { get; set; }
        public Nullable<bool> SalarioFlag { get; set; }
        public Nullable<int> TipoRubro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCuentasContablesPorEmpleadoYRubro> tCuentasContablesPorEmpleadoYRubroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNomina> tNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRubrosAsignado> tRubrosAsignados { get; set; }
    }
}
