//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNomina_SalarioIntegral
    {
        public int ID { get; set; }
        public int HeaderID { get; set; }
        public int Empleado { get; set; }
        public decimal SueldoBasico_Mensual { get; set; }
        public decimal SueldoBasico_Diario { get; set; }
        public short BonoVacacional_Dias { get; set; }
        public decimal BonoVacacional_Monto { get; set; }
        public decimal BonoVacacional_Diario { get; set; }
        public short Utilidades_Dias { get; set; }
        public decimal Utilidades_Monto { get; set; }
        public decimal Utilidades_Diario { get; set; }
        public decimal SalarioIntegral_Diario { get; set; }
        public decimal SalarioIntegral_Monto { get; set; }
    
        public virtual tNominaHeader tNominaHeader { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
