//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNomina
    {
        public int NumeroUnico { get; set; }
        public int HeaderID { get; set; }
        public int Empleado { get; set; }
        public int Rubro { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public Nullable<bool> AplicaPrestacionesFlag { get; set; }
        public Nullable<bool> MostrarEnElReciboFlag { get; set; }
        public Nullable<decimal> MontoBase { get; set; }
        public Nullable<byte> CantDias { get; set; }
        public Nullable<decimal> Fraccion { get; set; }
        public string Detalles { get; set; }
        public bool SueldoFlag { get; set; }
        public bool SalarioFlag { get; set; }
        public string VacFraccionFlag { get; set; }
        public Nullable<bool> FraccionarFlag { get; set; }
    
        public virtual tMaestraRubro tMaestraRubro { get; set; }
        public virtual tNominaHeader tNominaHeader { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
