//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPrestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPrestamo()
        {
            this.tCuotasPrestamos = new HashSet<tCuotasPrestamo>();
        }
    
        public int Numero { get; set; }
        public string Categoria { get; set; }
        public int Tipo { get; set; }
        public int Empleado { get; set; }
        public string Situacion { get; set; }
        public System.DateTime FechaSolicitado { get; set; }
        public Nullable<System.DateTime> FechaOtorgado { get; set; }
        public Nullable<System.DateTime> FechaCancelado { get; set; }
        public Nullable<System.DateTime> FechaAnulado { get; set; }
        public decimal MontoSolicitado { get; set; }
        public decimal MontoOtorgado { get; set; }
        public Nullable<decimal> PorcIntereses { get; set; }
        public decimal TotalAPagar { get; set; }
        public short NumeroDeCuotas { get; set; }
        public Nullable<decimal> MontoCuota { get; set; }
        public Nullable<decimal> MontoCancelado { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCuotasPrestamo> tCuotasPrestamos { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
