//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRubrosAsignado
    {
        public int RubroAsignado { get; set; }
        public int Empleado { get; set; }
        public int Rubro { get; set; }
        public string Descripcion { get; set; }
        public bool SuspendidoFlag { get; set; }
        public Nullable<short> OrdenDeAplicacion { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> SalarioFlag { get; set; }
        public string TipoNomina { get; set; }
        public string Periodicidad { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<bool> Siempre { get; set; }
        public decimal MontoAAplicar { get; set; }
    
        public virtual tMaestraRubro tMaestraRubro { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
