//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilidade
    {
        public int ID { get; set; }
        public int GrupoNomina { get; set; }
        public System.DateTime FechaNomina { get; set; }
        public System.DateTime Desde { get; set; }
        public System.DateTime Hasta { get; set; }
        public Nullable<decimal> CantidadMesesPeriodoPago { get; set; }
        public short CantidadDiasPeriodoPago { get; set; }
        public short CantidadDiasUtilidades { get; set; }
        public short BaseAplicacion { get; set; }
        public bool AplicarInce { get; set; }
        public decimal IncePorc { get; set; }
    
        public virtual tGruposEmpleado tGruposEmpleado { get; set; }
    }
}
