//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacacione
    {
        public int ClaveUnica { get; set; }
        public int Empleado { get; set; }
        public int GrupoNomina { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<System.DateTime> AnoVacacionesDesde { get; set; }
        public Nullable<System.DateTime> AnoVacacionesHasta { get; set; }
        public int AnoVacaciones { get; set; }
        public short NumeroVacaciones { get; set; }
        public Nullable<System.DateTime> Salida { get; set; }
        public Nullable<System.DateTime> Regreso { get; set; }
        public Nullable<short> CantDiasDisfrute_Feriados { get; set; }
        public Nullable<short> CantDiasDisfrute_SabDom { get; set; }
        public Nullable<short> CantDiasDisfrute_Habiles { get; set; }
        public short CantDiasDisfrute_Total { get; set; }
        public System.DateTime FechaReintegro { get; set; }
        public Nullable<System.DateTime> FechaNomina { get; set; }
        public Nullable<decimal> MontoBono { get; set; }
        public Nullable<bool> ObviarEnLaNominaFlag { get; set; }
        public Nullable<byte> CantDiasPago_YaTrabajados { get; set; }
        public Nullable<byte> CantDiasPago_Feriados { get; set; }
        public Nullable<byte> CantDiasPago_SabDom { get; set; }
        public Nullable<byte> CantDiasPago_Habiles { get; set; }
        public Nullable<short> CantDiasPago_Bono { get; set; }
        public Nullable<byte> CantDiasPago_Total { get; set; }
        public Nullable<byte> CantDiasAdicionales { get; set; }
        public Nullable<short> CantDiasVacPendAnosAnteriores { get; set; }
        public Nullable<short> CantDiasVacSegunTabla { get; set; }
        public Nullable<short> CantDiasVacDisfrutadosAntes { get; set; }
        public Nullable<short> CantDiasVacDisfrutadosAhora { get; set; }
        public Nullable<short> CantDiasVacPendientes { get; set; }
        public Nullable<bool> BonoVacacionalFlag { get; set; }
        public Nullable<System.DateTime> DesactivarNominaDesde { get; set; }
        public Nullable<System.DateTime> DesactivarNominaHasta { get; set; }
        public Nullable<bool> AplicarDeduccionesFlag { get; set; }
        public Nullable<System.DateTime> PeriodoPagoDesde { get; set; }
        public Nullable<System.DateTime> PeriodoPagoHasta { get; set; }
        public short PeriodoPagoDias { get; set; }
        public Nullable<short> CantDiasDeduccion { get; set; }
        public Nullable<System.DateTime> ProximaNomina_FechaNomina { get; set; }
        public Nullable<bool> ProximaNomina_AplicarDeduccionPorAnticipo { get; set; }
        public Nullable<byte> ProximaNomina_AplicarDeduccionPorAnticipo_CantDias { get; set; }
        public Nullable<bool> ProximaNomina_AplicarDeduccionesLegales { get; set; }
        public Nullable<byte> ProximaNomina_AplicarDeduccionesLegales_CantDias { get; set; }
    
        public virtual tGruposEmpleado tGruposEmpleado { get; set; }
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
