//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacacPorAnoParticulare
    {
        public int ClaveUnica { get; set; }
        public int Empleado { get; set; }
        public short Ano { get; set; }
        public int Dias { get; set; }
        public Nullable<short> DiasAdicionales { get; set; }
        public Nullable<short> DiasBono { get; set; }
    
        public virtual tEmpleado tEmpleado { get; set; }
    }
}
