//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Contab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbContabEntities : DbContext
    {
        public dbContabEntities()
            : base("name=dbContabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiento> Asientos { get; set; }
        public virtual DbSet<AsientosNegativosId> AsientosNegativosIds { get; set; }
        public virtual DbSet<Compania> Companias { get; set; }
        public virtual DbSet<dAsiento> dAsientos { get; set; }
        public virtual DbSet<MesesDelAnoFiscal> MesesDelAnoFiscals { get; set; }
        public virtual DbSet<UltimoMesCerradoContab> UltimoMesCerradoContabs { get; set; }
        public virtual DbSet<CuentasContable> CuentasContables { get; set; }
        public virtual DbSet<TiposDeAsiento> TiposDeAsientoes { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<tGruposDeTiposDeAsiento> tGruposDeTiposDeAsientoes { get; set; }
    }
}
