//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Contab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dAsiento
    {
        public int NumeroAutomatico { get; set; }
        public short Partida { get; set; }
        public int CuentaContableID { get; set; }
        public string Descripcion { get; set; }
        public string Referencia { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public Nullable<int> CentroCosto { get; set; }
        public Nullable<int> ConciliacionMovimientoID { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual CuentasContable CuentasContable { get; set; }
    }
}
