//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Contab
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesesDelAnoFiscal
    {
        public int ClaveUnica { get; set; }
        public short MesFiscal { get; set; }
        public short Mes { get; set; }
        public string NombreMes { get; set; }
        public short Ano { get; set; }
        public int Cia { get; set; }
    
        public virtual Compania Compania { get; set; }
    }
}
