//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Contab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGruposDeTiposDeAsiento
    {
        public tGruposDeTiposDeAsiento()
        {
            this.TiposDeAsientoes = new HashSet<TiposDeAsiento>();
        }
    
        public int Grupo { get; set; }
        public string Descripcion { get; set; }
        public int NumeroInicial { get; set; }
    
        public virtual ICollection<TiposDeAsiento> TiposDeAsientoes { get; set; }
    }
}
