//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaASP.Models.Contab
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDeAsiento
    {
        public TiposDeAsiento()
        {
            this.Asientos = new HashSet<Asiento>();
        }
    
        public Nullable<int> Grupo { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Asiento> Asientos { get; set; }
        public virtual tGruposDeTiposDeAsiento tGruposDeTiposDeAsiento { get; set; }
    }
}
